language: node_js
matrix:
  include:
    - node_js: "6.9.1"
    - node_js: "7"
    - node_js: "8"
dist: trusty
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  # TODO: remove after yarn is 1.0+ on Travis: https://github.com/travis-ci/travis-ci/issues/7566
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
before_script:
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # wait for xvfb to boot
addons:
  chrome: stable
